<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LexicalAnalyzer\LexicalAnalysis\LexicalAnalysis.csproj" />
    <ProjectReference Include="..\LexicalAnalyzer\LexicalMachine\LexicalMachine.csproj" />
    <ProjectReference Include="..\LexicalAnalyzer\Transliteration\Transliteration.csproj" />
  </ItemGroup>

</Project>
