<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LexicalAnalyzer\LexicalAnalysis\LexicalAnalysis.csproj" />
    <ProjectReference Include="..\LexicalAnalyzer\LexicalMachine\LexicalMachine.csproj" />
    <ProjectReference Include="..\LexicalAnalyzer\Transliteration\Transliteration.csproj" />
    <ProjectReference Include="..\Parser\Parsing.csproj" />
  </ItemGroup>

</Project>